version: "3"

services:

 ip2location-app:
    # build: .
    image: extrawurst/ip2location
    ports:
      - '8647:80'
    environment:
      PORT: '80'
    networks:
      - caddy

networks:
  caddy:
    external: true
